export interface VideoInfo {
  videoId: string;
  title: string;
  availableTracks: SubtitleTrack[];
}

export interface SubtitleTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  baseUrl: string;
}

export function trackDisplayName(track: SubtitleTrack): string {
  return track.languageName + (track.isAutoGenerated ? ' (auto)' : '');
}

export type Message =
  | { type: 'GET_VIDEO_INFO' }
  | { type: 'VIDEO_INFO_RESPONSE'; payload: VideoInfo | null }
  | { type: 'DOWNLOAD_SUBTITLE'; payload: { baseUrl: string; languageCode: string; format: 'srt' | 'txt'; title: string } }
  | { type: 'DOWNLOAD_RESULT'; payload: { success: boolean; error?: string } }
  | { type: 'GET_POT' }
  | { type: 'POT_RESPONSE'; payload: { pot: string | null } };
