import type { Message, VideoInfo, SubtitleTrack } from '../types/messages';

// Content script: runs on youtube.com pages.
// Detects the current video, extracts available subtitle tracks,
// and handles subtitle fetching + download.

let lastVideoId: string | null = null;

function getVideoId(): string | null {
  const url = new URL(window.location.href);
  return url.searchParams.get('v');
}

function extractPlayerResponse(): Record<string, unknown> | null {
  const scripts = Array.from(document.querySelectorAll('script'));
  for (const script of scripts) {
    const text = script.textContent ?? '';
    if (text.includes('ytInitialPlayerResponse')) {
      const match = text.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
      if (match) {
        try {
          return JSON.parse(match[1]) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function extractSubtitleTracks(playerResponse: Record<string, unknown>): SubtitleTrack[] {
  const captions = playerResponse['captions'];
  if (typeof captions !== 'object' || captions === null) return [];

  const renderer = (captions as Record<string, unknown>)['playerCaptionsTracklistRenderer'];
  if (typeof renderer !== 'object' || renderer === null) return [];

  const captionTracks = (renderer as Record<string, unknown>)['captionTracks'];
  if (!Array.isArray(captionTracks)) return [];

  const tracks: SubtitleTrack[] = [];
  for (const track of captionTracks) {
    if (typeof track !== 'object' || track === null) continue;
    const t = track as Record<string, unknown>;

    const baseUrl = t['baseUrl'];
    if (typeof baseUrl !== 'string') continue;

    const languageCode = typeof t['languageCode'] === 'string' ? t['languageCode'] : 'unknown';
    const isAutoGenerated = t['kind'] === 'asr';

    const name = t['name'];
    const languageName =
      typeof name === 'object' && name !== null && typeof (name as Record<string, unknown>)['simpleText'] === 'string'
        ? (name as Record<string, unknown>)['simpleText'] as string
        : languageCode;

    tracks.push({ languageCode, languageName, isAutoGenerated, baseUrl });
  }
  return tracks;
}

function buildVideoInfo(): VideoInfo | null {
  const videoId = getVideoId();
  if (!videoId) return null;
  const playerResponse = extractPlayerResponse();
  if (!playerResponse) return null;
  const tracks = extractSubtitleTracks(playerResponse);
  return {
    videoId,
    title: document.title.replace(' - YouTube', ''),
    availableTracks: tracks,
  };
}

// --- XML to SRT/TXT conversion ---

function unescapeHTML(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'");
}

function formatTime(timeInSec: number): string {
  const ms = Math.floor(timeInSec * 1000) % 1000;
  const totalSec = Math.floor(timeInSec);
  const hh = Math.floor(totalSec / 3600);
  const mm = Math.floor((totalSec - hh * 3600) / 60);
  const ss = totalSec - hh * 3600 - mm * 60;
  return (
    String(hh).padStart(2, '0') + ':' +
    String(mm).padStart(2, '0') + ':' +
    String(ss).padStart(2, '0') + ',' +
    String(ms).padStart(3, '0')
  );
}

function xmlToSrt(xml: string): string {
  const parser = new DOMParser();
  const doc = parser.parseFromString(xml, 'text/xml');
  const texts = Array.from(doc.getElementsByTagName('text'));

  let content = '';
  let count = 1;

  for (const el of texts) {
    const start = parseFloat(el.getAttribute('start') ?? '0');
    const dur = parseFloat(el.getAttribute('dur') ?? '0');
    const rawText = el.childNodes.length > 0 ? (el.childNodes[0].nodeValue ?? '') : '';
    const normalizedText = rawText.replace(/\\n/g, '\n').replace(/\\"/g, '"').trim();

    if (normalizedText) {
      const end = start + dur;
      content += count + '\n'
        + formatTime(start) + ' --> ' + formatTime(end) + '\n'
        + normalizedText + '\n\n';
      count++;
    }
  }

  return unescapeHTML(content);
}

function xmlToTxt(xml: string): string {
  const parser = new DOMParser();
  const doc = parser.parseFromString(xml, 'text/xml');
  const texts = Array.from(doc.getElementsByTagName('text'));
  const lines: string[] = [];

  for (const el of texts) {
    const rawText = el.childNodes.length > 0 ? (el.childNodes[0].nodeValue ?? '') : '';
    const normalizedText = rawText.replace(/\\n/g, '\n').replace(/\\"/g, '"').trim();
    if (normalizedText) {
      lines.push(normalizedText);
    }
  }

  return unescapeHTML(lines.join('\n') + '\n');
}

// --- Download via anchor click (runs in page context, reliable) ---

function saveTextAsFile(text: string, fileName: string): void {
  const blob = new Blob([text], { type: 'text/plain' });
  const href = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.download = fileName;
  link.href = href;
  link.style.display = 'none';
  link.addEventListener('click', () => {
    // Clean up after click event propagates
    setTimeout(() => {
      URL.revokeObjectURL(href);
      link.remove();
    }, 100);
  });
  document.body.appendChild(link);
  link.click();
}

// --- Download handler ---

async function downloadSubtitle(baseUrl: string, languageCode: string, format: 'srt' | 'txt'): Promise<void> {
  // Get pot token from background
  const potRequest: Message = { type: 'GET_POT' };
  const potResponse = await browser.runtime.sendMessage(potRequest) as Message;

  if (potResponse.type !== 'POT_RESPONSE' || !potResponse.payload.pot) {
    throw new Error('No POT token available. Please enable subtitles (CC button) and refresh the page.');
  }

  const fullUrl = baseUrl + '&fromExt=true&c=WEB&pot=' + potResponse.payload.pot;
  const response = await fetch(fullUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch subtitles: ${response.status}`);
  }
  const xml = await response.text();

  const content = format === 'srt' ? xmlToSrt(xml) : xmlToTxt(xml);
  const title = document.title.replace(/ - YouTube/gi, '');
  const safeTitle = title.replace(/[/\\:*?"<>|]/g, '_').trim();
  const fileName = `${safeTitle}.${languageCode}.${format}`;

  saveTextAsFile(content, fileName);
}

// --- In-page UI ---

const CONTAINER_ID = 'yt-subtitle-downloader';

function removeExistingUI(): void {
  document.getElementById(CONTAINER_ID)?.remove();
}

function findInsertionPoint(): Element | null {
  // Try known YouTube selectors for the area below the video title
  for (const selector of ['#bottom-row', '#meta #meta-contents #container #top-row']) {
    const el = document.querySelector(selector);
    if (el) return el;
  }
  return null;
}

function renderInPageUI(tracks: SubtitleTrack[]): void {
  removeExistingUI();

  const insertPoint = findInsertionPoint();
  if (!insertPoint) return;

  const container = document.createElement('div');
  container.id = CONTAINER_ID;
  container.style.cssText = 'padding:8px 0;margin:4px 0;font-size:13px;line-height:1.6;color:#aaa;display:flex;flex-wrap:wrap;align-items:center;gap:4px 0;';

  const label = document.createElement('span');
  label.textContent = 'Subtitles: ';
  label.style.marginRight = '6px';
  container.appendChild(label);

  if (tracks.length === 0) {
    const noSubs = document.createElement('span');
    noSubs.textContent = 'none available';
    noSubs.style.fontStyle = 'italic';
    container.appendChild(noSubs);
  } else {
    for (const track of tracks) {
      const link = document.createElement('a');
      link.textContent = track.languageName + (track.isAutoGenerated ? ' (auto)' : '');
      link.href = '#';
      link.style.cssText = 'margin-right:10px;cursor:pointer;color:#3ea6ff;text-decoration:none;font-size:13px;';
      link.addEventListener('mouseenter', () => { link.style.textDecoration = 'underline'; });
      link.addEventListener('mouseleave', () => { link.style.textDecoration = 'none'; });
      link.addEventListener('click', (e) => {
        e.preventDefault();
        link.style.color = '#aaa';
        link.textContent = 'Downloading...';
        downloadSubtitle(track.baseUrl, track.languageCode, 'srt')
          .then(() => {
            link.textContent = track.languageName + (track.isAutoGenerated ? ' (auto)' : '');
            link.style.color = '#3ea6ff';
          })
          .catch((err) => {
            link.textContent = 'Error';
            link.style.color = '#ff4444';
            console.error('Subtitle download failed:', err);
            setTimeout(() => {
              link.textContent = track.languageName + (track.isAutoGenerated ? ' (auto)' : '');
              link.style.color = '#3ea6ff';
            }, 3000);
          });
      });
      container.appendChild(link);
    }
  }

  insertPoint.parentNode?.insertBefore(container, insertPoint);
}

function checkAndRenderUI(): void {
  const videoId = getVideoId();
  if (!videoId) return;
  if (videoId === lastVideoId && document.getElementById(CONTAINER_ID)) return;

  if (!findInsertionPoint()) return;

  lastVideoId = videoId;
  const playerResponse = extractPlayerResponse();
  if (!playerResponse) {
    renderInPageUI([]);
    return;
  }
  const tracks = extractSubtitleTracks(playerResponse);
  renderInPageUI(tracks);
}

// Poll for URL changes and DOM readiness (YouTube is a SPA)
setInterval(checkAndRenderUI, 500);

// Also trigger on YouTube's SPA navigation event
window.addEventListener('yt-navigate-finish', () => {
  // Reset so checkAndRenderUI re-renders
  lastVideoId = null;
});

// --- Message listeners (for popup) ---

browser.runtime.onMessage.addListener((message: Message) => {
  if (message.type === 'GET_VIDEO_INFO') {
    const info = buildVideoInfo();
    const response: Message = { type: 'VIDEO_INFO_RESPONSE', payload: info };
    return Promise.resolve(response);
  }

  if (message.type === 'DOWNLOAD_SUBTITLE') {
    const { baseUrl, languageCode, format } = message.payload;
    return downloadSubtitle(baseUrl, languageCode, format)
      .then((): Message => ({ type: 'DOWNLOAD_RESULT', payload: { success: true } }))
      .catch((err: unknown): Message => {
        const error = err instanceof Error ? err.message : String(err);
        return { type: 'DOWNLOAD_RESULT', payload: { success: false, error } };
      });
  }

  return false;
});
