import type { SubtitleTrack } from '../types/messages';
import { YOUTUBE_WATCH_URL } from '../constants';

interface RawCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string };
}

const CAPTION_TRACKS_REGEX = /\{"captionTracks":(\[.*?\]),/;
let fetchAbortController: AbortController | null = null;

export async function fetchSubtitleTracks(videoId: string): Promise<SubtitleTrack[]> {
  // Fetch fresh page HTML to get current captionTracks data.
  // Parsing DOM script tags doesn't work after SPA navigation because YouTube
  // doesn't recreate <script> tags containing ytInitialPlayerResponse.
  fetchAbortController?.abort();
  fetchAbortController = new AbortController();

  const url = YOUTUBE_WATCH_URL + videoId;
  const html = await fetch(url, { signal: fetchAbortController.signal }).then((r) => r.text());
  const match = CAPTION_TRACKS_REGEX.exec(html);
  if (!match) return [];

  let raw: RawCaptionTrack[];
  try {
    raw = JSON.parse(match[1]) as RawCaptionTrack[];
  } catch {
    return [];
  }

  return raw
    .filter((t): t is RawCaptionTrack & { baseUrl: string } => typeof t.baseUrl === 'string')
    .map((t) => ({
      baseUrl: t.baseUrl,
      languageCode: t.languageCode ?? 'unknown',
      isAutoGenerated: t.kind === 'asr',
      languageName: t.name?.simpleText ?? t.languageCode ?? 'unknown',
    }));
}
