import type { SubtitleTrack } from '../types/messages';
import { YOUTUBE_WATCH_URL } from '../constants';

interface RawCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string };
}

const CAPTION_TRACKS_KEY = '"captionTracks":';
let fetchAbortController: AbortController | null = null;
const trackCache = new Map<string, SubtitleTrack[]>();
const pendingFetches = new Map<string, Promise<SubtitleTrack[]>>();

export function clearTrackCache(): void {
  trackCache.clear();
}

export async function fetchSubtitleTracks(videoId: string): Promise<SubtitleTrack[]> {
  if (trackCache.has(videoId)) {
    return trackCache.get(videoId)!;
  }

  // Deduplicate concurrent fetches for the same videoId
  const pending = pendingFetches.get(videoId);
  if (pending) return pending;

  const promise = doFetchSubtitleTracks(videoId);
  pendingFetches.set(videoId, promise);
  return promise.finally(() => pendingFetches.delete(videoId));
}

async function doFetchSubtitleTracks(videoId: string): Promise<SubtitleTrack[]> {
  // Fetch fresh page HTML to get current captionTracks data.
  // Parsing DOM script tags doesn't work after SPA navigation because YouTube
  // doesn't recreate <script> tags containing ytInitialPlayerResponse.
  fetchAbortController?.abort();
  fetchAbortController = new AbortController();

  const url = YOUTUBE_WATCH_URL + videoId;
  const response = await fetch(url, { signal: fetchAbortController.signal });
  if (!response.ok) {
    throw new Error(`Failed to fetch video page: ${response.status}`);
  }
  const html = await response.text();

  const captionJson = extractCaptionTracksJson(html);
  if (!captionJson) {
    trackCache.set(videoId, []);
    return [];
  }

  let raw: RawCaptionTrack[];
  try {
    raw = JSON.parse(captionJson) as RawCaptionTrack[];
  } catch (err) {
    console.warn('[YT Caption Saver] Failed to parse captionTracks JSON:', err);
    trackCache.set(videoId, []);
    return [];
  }

  const tracks = raw
    .filter((t): t is RawCaptionTrack & { baseUrl: string } => typeof t.baseUrl === 'string')
    .map((t) => ({
      baseUrl: t.baseUrl,
      languageCode: t.languageCode ?? 'unknown',
      isAutoGenerated: t.kind === 'asr',
      languageName: t.name?.simpleText ?? t.languageCode ?? 'unknown',
    }));

  trackCache.set(videoId, tracks);
  return tracks;
}

/** Extract the captionTracks JSON array using bracket balancing, skipping string contents. */
function extractCaptionTracksJson(html: string): string | null {
  const keyIndex = html.indexOf(CAPTION_TRACKS_KEY);
  if (keyIndex === -1) return null;

  const arrayStart = keyIndex + CAPTION_TRACKS_KEY.length;
  if (html[arrayStart] !== '[') return null;

  let depth = 0;
  let inString = false;
  for (let i = arrayStart; i < html.length; i++) {
    const ch = html[i];
    if (inString) {
      if (ch === '\\') { i++; continue; } // skip escaped character
      if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') { inString = true; continue; }
    if (ch === '[') depth++;
    else if (ch === ']') depth--;
    if (depth === 0) return html.slice(arrayStart, i + 1);
  }
  return null;
}
